import { createRouter, RouterProvider } from "@tanstack/react-router";
import { StrictMode } from "react";
import { createRoot } from "react-dom/client";
import "./index.css";
import { routeTree } from "./routeTree.gen";

// createRouter wires up the route tree generated by the Vite plugin
const router = createRouter({ routeTree });

// Registers the router type globally so Link, useNavigate, useSearch, etc.
// are all fully type-safe throughout the app
declare module "@tanstack/react-router" {
	interface Register {
		router: typeof router;
	}
}

createRoot(document.getElementById("root")!).render(
	<StrictMode>
		<RouterProvider router={router} />
	</StrictMode>,
);
