/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ToHopMonRouteImport } from './routes/to-hop-mon'
import { Route as TimKiemRouteImport } from './routes/tim-kiem'
import { Route as IndexRouteImport } from './routes/index'
import { Route as DanhSachTruongIndexRouteImport } from './routes/danh-sach-truong.index'
import { Route as DanhSachTruongSlugRouteImport } from './routes/danh-sach-truong.$slug'

const ToHopMonRoute = ToHopMonRouteImport.update({
  id: '/to-hop-mon',
  path: '/to-hop-mon',
  getParentRoute: () => rootRouteImport,
} as any)
const TimKiemRoute = TimKiemRouteImport.update({
  id: '/tim-kiem',
  path: '/tim-kiem',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const DanhSachTruongIndexRoute = DanhSachTruongIndexRouteImport.update({
  id: '/danh-sach-truong/',
  path: '/danh-sach-truong/',
  getParentRoute: () => rootRouteImport,
} as any)
const DanhSachTruongSlugRoute = DanhSachTruongSlugRouteImport.update({
  id: '/danh-sach-truong/$slug',
  path: '/danh-sach-truong/$slug',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/tim-kiem': typeof TimKiemRoute
  '/to-hop-mon': typeof ToHopMonRoute
  '/danh-sach-truong/$slug': typeof DanhSachTruongSlugRoute
  '/danh-sach-truong/': typeof DanhSachTruongIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/tim-kiem': typeof TimKiemRoute
  '/to-hop-mon': typeof ToHopMonRoute
  '/danh-sach-truong/$slug': typeof DanhSachTruongSlugRoute
  '/danh-sach-truong': typeof DanhSachTruongIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/tim-kiem': typeof TimKiemRoute
  '/to-hop-mon': typeof ToHopMonRoute
  '/danh-sach-truong/$slug': typeof DanhSachTruongSlugRoute
  '/danh-sach-truong/': typeof DanhSachTruongIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/tim-kiem'
    | '/to-hop-mon'
    | '/danh-sach-truong/$slug'
    | '/danh-sach-truong/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/tim-kiem'
    | '/to-hop-mon'
    | '/danh-sach-truong/$slug'
    | '/danh-sach-truong'
  id:
    | '__root__'
    | '/'
    | '/tim-kiem'
    | '/to-hop-mon'
    | '/danh-sach-truong/$slug'
    | '/danh-sach-truong/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  TimKiemRoute: typeof TimKiemRoute
  ToHopMonRoute: typeof ToHopMonRoute
  DanhSachTruongSlugRoute: typeof DanhSachTruongSlugRoute
  DanhSachTruongIndexRoute: typeof DanhSachTruongIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/to-hop-mon': {
      id: '/to-hop-mon'
      path: '/to-hop-mon'
      fullPath: '/to-hop-mon'
      preLoaderRoute: typeof ToHopMonRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tim-kiem': {
      id: '/tim-kiem'
      path: '/tim-kiem'
      fullPath: '/tim-kiem'
      preLoaderRoute: typeof TimKiemRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/danh-sach-truong/': {
      id: '/danh-sach-truong/'
      path: '/danh-sach-truong'
      fullPath: '/danh-sach-truong/'
      preLoaderRoute: typeof DanhSachTruongIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/danh-sach-truong/$slug': {
      id: '/danh-sach-truong/$slug'
      path: '/danh-sach-truong/$slug'
      fullPath: '/danh-sach-truong/$slug'
      preLoaderRoute: typeof DanhSachTruongSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  TimKiemRoute: TimKiemRoute,
  ToHopMonRoute: ToHopMonRoute,
  DanhSachTruongSlugRoute: DanhSachTruongSlugRoute,
  DanhSachTruongIndexRoute: DanhSachTruongIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
