/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ToHopMonRouteImport } from './routes/to-hop-mon'
import { Route as TimKiemRouteImport } from './routes/tim-kiem'
import { Route as DanhSachTruongRouteImport } from './routes/danh-sach-truong'
import { Route as IndexRouteImport } from './routes/index'
import { Route as DanhSachTruongIndexRouteImport } from './routes/danh-sach-truong.index'
import { Route as DanhSachTruongUniversityIdRouteImport } from './routes/danh-sach-truong.$universityId'

const ToHopMonRoute = ToHopMonRouteImport.update({
  id: '/to-hop-mon',
  path: '/to-hop-mon',
  getParentRoute: () => rootRouteImport,
} as any)
const TimKiemRoute = TimKiemRouteImport.update({
  id: '/tim-kiem',
  path: '/tim-kiem',
  getParentRoute: () => rootRouteImport,
} as any)
const DanhSachTruongRoute = DanhSachTruongRouteImport.update({
  id: '/danh-sach-truong',
  path: '/danh-sach-truong',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const DanhSachTruongIndexRoute = DanhSachTruongIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => DanhSachTruongRoute,
} as any)
const DanhSachTruongUniversityIdRoute =
  DanhSachTruongUniversityIdRouteImport.update({
    id: '/$universityId',
    path: '/$universityId',
    getParentRoute: () => DanhSachTruongRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/danh-sach-truong': typeof DanhSachTruongRouteWithChildren
  '/tim-kiem': typeof TimKiemRoute
  '/to-hop-mon': typeof ToHopMonRoute
  '/danh-sach-truong/$universityId': typeof DanhSachTruongUniversityIdRoute
  '/danh-sach-truong/': typeof DanhSachTruongIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/tim-kiem': typeof TimKiemRoute
  '/to-hop-mon': typeof ToHopMonRoute
  '/danh-sach-truong/$universityId': typeof DanhSachTruongUniversityIdRoute
  '/danh-sach-truong': typeof DanhSachTruongIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/danh-sach-truong': typeof DanhSachTruongRouteWithChildren
  '/tim-kiem': typeof TimKiemRoute
  '/to-hop-mon': typeof ToHopMonRoute
  '/danh-sach-truong/$universityId': typeof DanhSachTruongUniversityIdRoute
  '/danh-sach-truong/': typeof DanhSachTruongIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/danh-sach-truong'
    | '/tim-kiem'
    | '/to-hop-mon'
    | '/danh-sach-truong/$universityId'
    | '/danh-sach-truong/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/tim-kiem'
    | '/to-hop-mon'
    | '/danh-sach-truong/$universityId'
    | '/danh-sach-truong'
  id:
    | '__root__'
    | '/'
    | '/danh-sach-truong'
    | '/tim-kiem'
    | '/to-hop-mon'
    | '/danh-sach-truong/$universityId'
    | '/danh-sach-truong/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  DanhSachTruongRoute: typeof DanhSachTruongRouteWithChildren
  TimKiemRoute: typeof TimKiemRoute
  ToHopMonRoute: typeof ToHopMonRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/to-hop-mon': {
      id: '/to-hop-mon'
      path: '/to-hop-mon'
      fullPath: '/to-hop-mon'
      preLoaderRoute: typeof ToHopMonRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tim-kiem': {
      id: '/tim-kiem'
      path: '/tim-kiem'
      fullPath: '/tim-kiem'
      preLoaderRoute: typeof TimKiemRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/danh-sach-truong': {
      id: '/danh-sach-truong'
      path: '/danh-sach-truong'
      fullPath: '/danh-sach-truong'
      preLoaderRoute: typeof DanhSachTruongRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/danh-sach-truong/': {
      id: '/danh-sach-truong/'
      path: '/'
      fullPath: '/danh-sach-truong/'
      preLoaderRoute: typeof DanhSachTruongIndexRouteImport
      parentRoute: typeof DanhSachTruongRoute
    }
    '/danh-sach-truong/$universityId': {
      id: '/danh-sach-truong/$universityId'
      path: '/$universityId'
      fullPath: '/danh-sach-truong/$universityId'
      preLoaderRoute: typeof DanhSachTruongUniversityIdRouteImport
      parentRoute: typeof DanhSachTruongRoute
    }
  }
}

interface DanhSachTruongRouteChildren {
  DanhSachTruongUniversityIdRoute: typeof DanhSachTruongUniversityIdRoute
  DanhSachTruongIndexRoute: typeof DanhSachTruongIndexRoute
}

const DanhSachTruongRouteChildren: DanhSachTruongRouteChildren = {
  DanhSachTruongUniversityIdRoute: DanhSachTruongUniversityIdRoute,
  DanhSachTruongIndexRoute: DanhSachTruongIndexRoute,
}

const DanhSachTruongRouteWithChildren = DanhSachTruongRoute._addFileChildren(
  DanhSachTruongRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  DanhSachTruongRoute: DanhSachTruongRouteWithChildren,
  TimKiemRoute: TimKiemRoute,
  ToHopMonRoute: ToHopMonRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
