/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ToHopMonRouteImport } from './routes/to-hop-mon'
import { Route as TimKiemRouteImport } from './routes/tim-kiem'
import { Route as DanhSachTruongRouteImport } from './routes/danh-sach-truong'
import { Route as IndexRouteImport } from './routes/index'

const ToHopMonRoute = ToHopMonRouteImport.update({
  id: '/to-hop-mon',
  path: '/to-hop-mon',
  getParentRoute: () => rootRouteImport,
} as any)
const TimKiemRoute = TimKiemRouteImport.update({
  id: '/tim-kiem',
  path: '/tim-kiem',
  getParentRoute: () => rootRouteImport,
} as any)
const DanhSachTruongRoute = DanhSachTruongRouteImport.update({
  id: '/danh-sach-truong',
  path: '/danh-sach-truong',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/danh-sach-truong': typeof DanhSachTruongRoute
  '/tim-kiem': typeof TimKiemRoute
  '/to-hop-mon': typeof ToHopMonRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/danh-sach-truong': typeof DanhSachTruongRoute
  '/tim-kiem': typeof TimKiemRoute
  '/to-hop-mon': typeof ToHopMonRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/danh-sach-truong': typeof DanhSachTruongRoute
  '/tim-kiem': typeof TimKiemRoute
  '/to-hop-mon': typeof ToHopMonRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/danh-sach-truong' | '/tim-kiem' | '/to-hop-mon'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/danh-sach-truong' | '/tim-kiem' | '/to-hop-mon'
  id: '__root__' | '/' | '/danh-sach-truong' | '/tim-kiem' | '/to-hop-mon'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  DanhSachTruongRoute: typeof DanhSachTruongRoute
  TimKiemRoute: typeof TimKiemRoute
  ToHopMonRoute: typeof ToHopMonRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/to-hop-mon': {
      id: '/to-hop-mon'
      path: '/to-hop-mon'
      fullPath: '/to-hop-mon'
      preLoaderRoute: typeof ToHopMonRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tim-kiem': {
      id: '/tim-kiem'
      path: '/tim-kiem'
      fullPath: '/tim-kiem'
      preLoaderRoute: typeof TimKiemRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/danh-sach-truong': {
      id: '/danh-sach-truong'
      path: '/danh-sach-truong'
      fullPath: '/danh-sach-truong'
      preLoaderRoute: typeof DanhSachTruongRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  DanhSachTruongRoute: DanhSachTruongRoute,
  TimKiemRoute: TimKiemRoute,
  ToHopMonRoute: ToHopMonRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
